version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get -t -d -v ./...
      - run: go test -v -cover ./...
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: go get -v
      - run: go build -v
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
        requires:
          - test
