version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/sweetim/tar-server
    steps:
      - checkout

      - run: go get -v
      - run: go build -v
  test:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/sweetim/tar-server
    steps:
      - checkout

      - run: go get -v
      - run: go test -v -cover ./...
  deploy:
    machine: true
    working_directory: /go/src/github.com/sweetim/tar-server
    steps:
      - checkout

      - run: |
          docker login -u $USERNAME -p $PASSWORD
          docker build -t timx/tar-server .
          docker push timx/tar-server
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
